apiVersion: v1
kind: Pod
metadata:
        name: resultapp-pod
        labels:
          name: resultapp-pod
          app: demo-voting-app
spec:
   containers:
     - name: result-app
       image: dockersamples/examplevotingapp_result
       ports:
         - containerPort: 80

